CREATE TABLE IF NOT EXISTS users(
   id BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   login  VARCHAR(100) NOT NULL UNIQUE,
   password VARCHAR(100) NOT NULL
);

CREATE TYPE mode_enum AS ENUM('income', 'expense');

CREATE TABLE IF NOT EXISTS finance(
   id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   title VARCHAR(100) NOT NULL,
   amount DECIMAL(11, 2),
   mode mode_enum,
   datee DATE DEFAULT CURRENT_DATE,
   user_id BIGINT NOT NULL,

   CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES users(id)
)